name: gh-pages
on:
  push:
    branches: [ master ]

  workflow_dispatch

jobs:
  deplay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install deps
        run: npm ci

      - run: |
          mkdir dist \
          && npx -c "NO_MULTIPLAYER=true babel js --out-dir ./dist/js" \
          && cp -r css ./dist/css \
          && cp -r images ./dist/images \
          && cp index.html ./dist/index.html

      - name: Deploy 🚀
        id: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
